### PR TITLE
Routed errors to Middleware

### PR DESCRIPTION
**Pull request by DebadityaPal**
I have routed all the errors thrown by the controllers to the errorHandler Middleware. Solves #6

### CODE REVIEW

**Comment by GunaShekar02** [comment]
Hey @DebadityaPal, just a couple of issues.
1. Could you please add semicolons to all the next(err) statements? If you use VSCode, ctrl+shift+i should do the trick if you have auto-format enabled.
2. In `server/api/middlewares/error.handler.js`, the format for returning the error is slightly different from what we used earlier, which fails the unit tests. Could you change that to the previous format?
Previous format:-
```
res.status(err.status || 500).json({
        message: err.message || "Something went wrong, please try again.",
      });
```
instead of what's given there.

**Comment by DebadityaPal** [comment]
I have a slight doubt in one case. The middleware has a const called errors that takes the values of either the err.errors or the err.message. The previous error format used only the err.message. Will the newer format use this constant? if so, will it pass the tests?

**Comment by GunaShekar02** [comment]
We won't need that const anymore. We can directly use the err parameter that is received by the middleware function and write the exact code as in my last comment. The err parameter received by the function will have the status and message properties attached to it.

**Comment by DebadityaPal** [comment]
I have made the necessary changes.

**Comment by GunaShekar02** [comment]
Looks great! Merged

**Pull request merged**
